/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.sales;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Business.Business;
import model.CustomerManagement.CustomerDirectory;
import model.CustomerManagement.CustomerProfile;
import model.OrderManagement.MasterOrderList;
import model.OrderManagement.Order;
import model.Personnel.Person;
import model.Personnel.PersonDirectory;
import model.ProductManagement.ProductCatalog;
import model.SalesManagement.SalesPersonProfile;
import model.Supplier.SupplierDirectory;
import model.Supplier.SupplierProfile;

/**
 *
 * @author Ram
 */
public class Salesworkpanel extends javax.swing.JPanel {

    /**
     * Creates new form Salesworkpanel
     */
    JPanel userProcessContainer;
    Business business;
    SalesPersonProfile sales;
 

    public Salesworkpanel(JPanel u, Business d, SalesPersonProfile s) {
initComponents();   
    business=d;
    userProcessContainer=u;
    sales=s;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Sim1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sales Person Menu");

        jButton1.setText("Suppliers and Products list");

        Sim1.setText("Run Simulation 1");
        Sim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sim1ActionPerformed(evt);
            }
        });

        jButton3.setText("Sales Dashboard");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(Sim1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sim1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(321, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String s= jTextField1.getText();
        if(s==null){JOptionPane.showMessageDialog(null, "Please valid customer detail", "Warning", JOptionPane.WARNING_MESSAGE);
            return;}
        CustomerProfile cp = business.getCustomerDirectory().findCustomer(s);
        productperformanceJPanel cwjp = new productperformanceJPanel(userProcessContainer, business,cp);
//            userProcessContainer.removeAll();
            userProcessContainer.add("ppj", cwjp);
            ((java.awt.CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Sim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sim1ActionPerformed
        // TODO add your handling code here:
        MasterOrderList mol =  business.getMasterOrderList();
        PersonDirectory persondirectory = business.getPersonDirectory();
        Person p17 = persondirectory.newPerson("Ryan Gonzalez");
        Person p18 = persondirectory.newPerson("Taylor Flores");
        Person p19 = persondirectory.newPerson("Justin Nguyen");
        Person p20 = persondirectory.newPerson("Hannah Kim");
        
        SupplierDirectory supplierdirectory = business.getSupplierDirectory();
        SupplierProfile supp= supplierdirectory.findSupplier("Will");
        
        CustomerDirectory customerdirectory = business.getCustomerDirectory();
        CustomerProfile customerprofile0 = customerdirectory.newCustomerProfile(p17);
        CustomerProfile customerprofile1 = customerdirectory.newCustomerProfile(p18);
        
        ProductCatalog pc = supp.getProductCatalog();
        Order order1 = mol.newOrder(customerprofile0,sales);
        
        order1.newOrderItem(newProduct1,1050 ,3);
        Order order1 = mol.newOrder(customerprofile0,salesperson1);
        
        order1.newOrderItem(newProduct1,1050 ,3); 
    }//GEN-LAST:event_Sim1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sim1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
